/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/research/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Research */
        post: operations["start_research_api_research__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research History */
        get: operations["research_history_api_research_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Research Stream */
        post: operations["start_research_stream_api_research_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Detail */
        get: operations["research_detail_api_research__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{session_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Followup Chat */
        post: operations["followup_chat_api_research__session_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Messages */
        get: operations["research_messages_api_research__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research History */
        get: operations["research_history_api_v1_research_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_research_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Task */
        get: operations["get_active_task_api_v1_research_tasks_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_research_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_v1_research_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_v1_research_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Task */
        post: operations["cancel_task_api_v1_research_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_v1_research_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Task */
        get: operations["export_task_api_v1_research_tasks__task_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Followup */
        put: operations["put_followup_api_v1_research_tasks__task_id__follow_up_put"];
        post?: never;
        /** Cancel Followup */
        delete: operations["cancel_followup_api_v1_research_tasks__task_id__follow_up_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages */
        get: operations["messages_api_v1_research_tasks__task_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_v1_research_tasks__task_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Task */
        post: operations["retry_task_api_v1_research_tasks__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/deepseek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deepseek Settings */
        get: operations["get_deepseek_settings_api_v1_settings_deepseek_get"];
        /** Update Deepseek Settings */
        put: operations["update_deepseek_settings_api_v1_settings_deepseek_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcademicSource
         * @enum {string}
         */
        AcademicSource: "arxiv" | "semantic_scholar" | "pubmed" | "crossref";
        /** AnalysisFindingResponse */
        AnalysisFindingResponse: {
            /** Claim Ids */
            claim_ids?: string[];
            /**
             * Finding Id
             * @default
             */
            finding_id: string;
            /**
             * Kind
             * @default gap
             */
            kind: string;
            /** Paper Ids */
            paper_ids?: string[];
            /**
             * Statement
             * @default
             */
            statement: string;
            /**
             * Support Type
             * @default unverified
             */
            support_type: string;
            /**
             * Valid
             * @default true
             */
            valid: boolean;
        };
        /** CitationResponse */
        CitationResponse: {
            /** Chunk Ids */
            chunk_ids?: string[];
            /**
             * Citation Id
             * @default
             */
            citation_id: string;
            /** Claim Ids */
            claim_ids?: string[];
            /** Display Number */
            display_number?: number | null;
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * Paper Id
             * @default
             */
            paper_id: string;
            /**
             * Section Id
             * @default
             */
            section_id: string;
            /**
             * Support Type
             * @default direct
             */
            support_type: string;
            /**
             * Valid
             * @default true
             */
            valid: boolean;
            /** Validation Message */
            validation_message?: string | null;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Citations */
            citations?: string[];
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Message Id */
            message_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ConversationSnapshot */
        ConversationSnapshot: {
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
            pending?: components["schemas"]["PendingFollowUp"] | null;
            /** Task Id */
            task_id: string;
            /** Task Status */
            task_status: string;
        };
        /** CreateResearchTaskRequest */
        CreateResearchTaskRequest: {
            /** Client Request Id */
            client_request_id: string;
            options?: components["schemas"]["ResearchTaskOptions"];
            /** Query */
            query: string;
        };
        /** CreateTaskResponse */
        CreateTaskResponse: {
            links: components["schemas"]["TaskLinks"];
            task: components["schemas"]["TaskSnapshot"];
        };
        /** DeepSeekSettingsResponse */
        DeepSeekSettingsResponse: {
            /** Api Key Configured */
            api_key_configured: boolean;
            /** Api Key Required */
            api_key_required: boolean;
            /** Default Model */
            default_model: string;
            /**
             * Provider
             * @default deepseek
             * @constant
             */
            provider: "deepseek";
        };
        /**
         * EventLevel
         * @enum {string}
         */
        EventLevel: "info" | "warning" | "error";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "agent.delegated" | "task.created" | "task.started" | "task.cancellation_requested" | "task.cancelled" | "task.completed" | "task.failed" | "task.interrupted" | "stage.started" | "stage.progress" | "stage.warning" | "stage.completed" | "stage.failed" | "plan.available" | "papers.discovered" | "papers.selected" | "paper.read" | "analysis.available" | "draft.available" | "critique.completed" | "evidence.available" | "result.available";
        /** EvidenceResponse */
        EvidenceResponse: {
            /**
             * Chunk Id
             * @default
             */
            chunk_id: string;
            /** Claim Id */
            claim_id?: string | null;
            /**
             * Content Type
             * @default pdf
             */
            content_type: string;
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            /**
             * Paper Id
             * @default
             */
            paper_id: string;
            /**
             * Support Type
             * @default unverified
             */
            support_type: string;
            /**
             * Task Id
             * @default
             */
            task_id: string;
            /** Validation Message */
            validation_message?: string | null;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /** FollowUpRequest */
        FollowUpRequest: {
            /** Message */
            message: string;
            /** Message Id */
            message_id: string;
        };
        /** FollowUpResponse */
        FollowUpResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations?: string[];
            /** Mode */
            mode: string;
            /** Session Id */
            session_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaperClaimResponse */
        PaperClaimResponse: {
            /** Chunk Ids */
            chunk_ids?: string[];
            /**
             * Claim Id
             * @default
             */
            claim_id: string;
            /** Evidence Text */
            evidence_text?: string | null;
            /**
             * Paper Id
             * @default
             */
            paper_id: string;
            /**
             * Statement
             * @default
             */
            statement: string;
            /**
             * Support Type
             * @default unverified
             */
            support_type: string;
            /**
             * Valid
             * @default true
             */
            valid: boolean;
        };
        /** PendingFollowUp */
        PendingFollowUp: {
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Message Id */
            message_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "failed";
        };
        /** ReadProgressPayload */
        ReadProgressPayload: {
            /** Attempt */
            attempt: number;
            /** Completed */
            completed: number;
            /** Degraded */
            degraded: number;
            /** Failed */
            failed: number;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Succeeded */
            succeeded: number;
            /** Total */
            total: number;
        };
        /** ReportSectionResponse */
        ReportSectionResponse: {
            /** Citation Ids */
            citation_ids?: string[];
            /**
             * Heading
             * @default
             */
            heading: string;
            /**
             * Level
             * @default 1
             */
            level: number;
            /**
             * Markdown
             * @default
             */
            markdown: string;
            /**
             * Section Id
             * @default
             */
            section_id: string;
        };
        /** ResearchEvent */
        ResearchEvent: {
            event_type: components["schemas"]["EventType"];
            /** @default info */
            level: components["schemas"]["EventLevel"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | components["schemas"]["ReadProgressPayload"];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Sequence */
            sequence: number;
            /** @default null */
            stage: components["schemas"]["ResearchStage"] | null;
            /** Task Id */
            task_id: string;
        };
        /**
         * ResearchPaperResult
         * @description Typed contract for the fields a structured paper result may expose.
         */
        ResearchPaperResult: {
            /** Abstract */
            abstract?: string | null;
            /** Aliases */
            aliases?: {
                [key: string]: unknown;
            }[];
            /** Authors */
            authors?: string[];
            /** Canonical Id */
            canonical_id?: string | null;
            /** Citation Count */
            citation_count?: number | null;
            /** Doi */
            doi?: string | null;
            /**
             * Full Text Status
             * @default unavailable
             */
            full_text_status: string;
            /** Landing Page Url */
            landing_page_url?: string | null;
            /**
             * Paper Id
             * @default
             */
            paper_id: string;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Relevance Reason */
            relevance_reason?: string | null;
            /** Relevance Score */
            relevance_score?: number | null;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Source Id
             * @default
             */
            source_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Year */
            year?: number | null;
        };
        /** ResearchRequest */
        ResearchRequest: {
            /**
             * Max Papers
             * @default 15
             */
            max_papers: number;
            /**
             * Query
             * @description research question
             */
            query: string;
        };
        /** ResearchResponse */
        ResearchResponse: {
            /** Final Answer */
            final_answer: string;
            /** Papers Count */
            papers_count: number;
            /** Research Plan */
            research_plan: {
                [key: string]: unknown;
            }[];
            /** Session Id */
            session_id: string;
        };
        /**
         * ResearchStage
         * @enum {string}
         */
        ResearchStage: "orchestrate" | "search" | "filter" | "read" | "analyze" | "synthesize" | "critic";
        /** ResearchTaskOptions */
        ResearchTaskOptions: {
            /**
             * Max Papers
             * @default 15
             */
            max_papers: number;
            /**
             * Output Language
             * @default auto
             * @enum {string}
             */
            output_language: "auto" | "zh-CN" | "en";
            /** Sources */
            sources?: components["schemas"]["AcademicSource"][];
        };
        /** ResearchTaskResultResponse */
        ResearchTaskResultResponse: {
            /** Analysis */
            analysis?: {
                [key: string]: unknown;
            };
            /** Analysis Findings */
            analysis_findings?: components["schemas"]["AnalysisFindingResponse"][];
            capabilities?: components["schemas"]["ResultCapabilities"];
            /** Citations */
            citations?: components["schemas"]["CitationResponse"][];
            /** Critique */
            critique?: {
                [key: string]: unknown;
            };
            /** Evidence */
            evidence?: components["schemas"]["EvidenceResponse"][];
            /** Paper Claims */
            paper_claims?: components["schemas"]["PaperClaimResponse"][];
            /** Paper Insights */
            paper_insights?: {
                [key: string]: unknown;
            }[];
            /** Papers */
            papers?: components["schemas"]["ResearchPaperResult"][];
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /**
             * Report Markdown
             * @default
             */
            report_markdown: string;
            /** Research Plan */
            research_plan?: {
                [key: string]: unknown;
            }[];
            /** Run Metadata */
            run_metadata?: {
                [key: string]: unknown;
            };
            /** Statistics */
            statistics?: {
                [key: string]: unknown;
            };
            structured_report?: components["schemas"]["StructuredReportResponse"];
            /** Task Id */
            task_id: string;
            /** Warnings */
            warnings?: string[];
        };
        /** ResultCapabilities */
        ResultCapabilities: {
            /**
             * Supports Evidence
             * @default false
             */
            supports_evidence: boolean;
            /**
             * Supports Replay
             * @default false
             */
            supports_replay: boolean;
            /**
             * Supports Structured Papers
             * @default false
             */
            supports_structured_papers: boolean;
        };
        /** StageSnapshot */
        StageSnapshot: {
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /** Completed At */
            completed_at?: string | null;
            /** Detail */
            detail?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            stage: components["schemas"]["ResearchStage"];
            /** Started At */
            started_at?: string | null;
            /** @default pending */
            status: components["schemas"]["StageStatus"];
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "pending" | "running" | "completed" | "warning" | "failed" | "cancelled";
        /** StructuredReportResponse */
        StructuredReportResponse: {
            /** Citations */
            citations?: components["schemas"]["CitationResponse"][];
            /**
             * Markdown
             * @default
             */
            markdown: string;
            /** Sections */
            sections?: components["schemas"]["ReportSectionResponse"][];
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** TaskLinks */
        TaskLinks: {
            /** Events */
            events: string;
            /** Result */
            result: string;
            /** Self */
            self: string;
        };
        /** TaskProgress */
        TaskProgress: {
            /** Message */
            message?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
        };
        /** TaskSnapshot */
        TaskSnapshot: {
            /** Available Actions */
            available_actions?: string[];
            /** Client Request Id */
            client_request_id: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            current_stage?: components["schemas"]["ResearchStage"] | null;
            /**
             * Effective Locale
             * @default en
             * @enum {string}
             */
            effective_locale: "zh-CN" | "en";
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /**
             * Last Sequence
             * @default 0
             */
            last_sequence: number;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            /** Parent Task Id */
            parent_task_id?: string | null;
            progress?: components["schemas"]["TaskProgress"];
            /** Query */
            query: string;
            /** Replay Events */
            replay_events?: {
                [key: string]: unknown;
            }[];
            /** Stages */
            stages?: components["schemas"]["StageSnapshot"][];
            /** Started At */
            started_at?: string | null;
            /** Statistics */
            statistics?: {
                [key: string]: unknown;
            };
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled" | "interrupted";
        /** UpdateDeepSeekSettingsRequest */
        UpdateDeepSeekSettingsRequest: {
            /** Api Key */
            api_key: string;
        };
        /** UpdateTaskRequest */
        UpdateTaskRequest: {
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_research_api_research__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_history_api_research_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_research_stream_api_research_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_detail_api_research__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    followup_chat_api_research__session_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_messages_api_research__session_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_history_api_v1_research_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_research_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResearchTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_task_api_v1_research_tasks_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description No active task */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_task_api_v1_research_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_research_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_research_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_research_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_research_tasks__task_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_task_api_v1_research_tasks__task_id__export_get: {
        parameters: {
            query?: {
                format?: "markdown" | "bibtex" | "json";
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_followup_api_v1_research_tasks__task_id__follow_up_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_followup_api_v1_research_tasks__task_id__follow_up_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    messages_api_v1_research_tasks__task_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v1_research_tasks__task_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchTaskResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_task_api_v1_research_tasks__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deepseek_settings_api_v1_settings_deepseek_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepSeekSettingsResponse"];
                };
            };
        };
    };
    update_deepseek_settings_api_v1_settings_deepseek_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeepSeekSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepSeekSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
