import {spawnSync} from "node:child_process";
import {existsSync} from "node:fs";
import {fileURLToPath} from "node:url";
import path from "node:path";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const local = path.join(root, process.platform === "win32" ? ".venv/Scripts/python.exe" : ".venv/bin/python");
const python = process.env.PYTHON_EXE || (existsSync(local) ? local : "python");
const result = spawnSync(python, [path.join(root, "scripts/export_openapi.py")], {cwd: root, stdio: "inherit"});
if (result.error) console.error(result.error.message);
process.exit(result.status ?? 1);
